import tabsdata as td


@td.transformer(
    input_tables=["bronze/clients_bronze"],
    output_tables=["clients_silver"],
)
def clients_silver_trf(clients_bronze: td.TableFrame) -> td.TableFrame:
    clients_silver = clients_bronze.select(
        [
            "Id",
            "UniqueId",
            "FirstName",
            "MiddleName",
            "LastName",
            "Email",
            "BirthDate",
            "Gender",
            "MobilePhone",
            "HomePhone",
            "WorkPhone",
            "WorkExtension",
            "AddressLine1",
            "AddressLine2",
            "City",
            "State",
            "PostalCode",
            "Country",
            "Active",
            "Status",
            "Action",
            "IsCompany",
            "IsProspect",
            "CreationDate",
            "LastModifiedDateTime",
            "FirstAppointmentDate",
            "FirstClassDate",
            "AccountBalance",
            "SuspensionInfo__BookingSuspended",
            "SuspensionInfo__SuspensionStartDate",
            "SuspensionInfo__SuspensionEndDate",
            "RedAlert",
            "YellowAlert",
            "Notes",
            "LiabilityRelease",
            "Liability__AgreementDate",
            "Liability__IsReleased",
            "SendAccountEmails",
            "SendAccountTexts",
            "SendPromotionalEmails",
            "SendPromotionalTexts",
            "SendScheduleEmails",
            "SendScheduleTexts",
            "HomeLocation__Id",
            "HomeLocation__Name",
            "HomeLocation__City",
            "HomeLocation__StateProvCode",
            "HomeLocation__SiteID",
            "ClientType__Id",
            "ClientType__Name",
            "ProspectStage__Id",
            "ProspectStage__Description",
            "ProspectStage__Active",
            "EmergencyContactInfoName",
            "EmergencyContactInfoEmail",
            "EmergencyContactInfoPhone",
            "EmergencyContactInfoRelationship",
            "AppointmentGenderPreference",
            "MembershipIcon",
            "ReferredBy",
        ]
    )

    return clients_silver
